// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.unmango.commandx.remote.enums;

import com.pulumi.core.annotations.EnumType;
import java.lang.String;
import java.util.Objects;
import java.util.StringJoiner;

    @EnumType
    public enum SystemctlCommand {
        Bind("bind"),
        Cat("cat"),
        Clean("clean"),
        Daemonreload("daemon-reload"),
        Disable("disable"),
        Enable("enable"),
        Freeze("freeze"),
        Isactive("is-active"),
        Isenabled("is-enabled"),
        Isfailed("is-failed"),
        Isolate("isolate"),
        Kill("kill"),
        Listautomounts("list-automounts"),
        Listdependencies("list-dependencies"),
        Listpaths("list-paths"),
        Listsockets("list-sockets"),
        Listtimers("list-timers"),
        Listunits("list-units"),
        Mask("mask"),
        Mountimage("mount-image"),
        Reenable("reenable"),
        Reload("reload"),
        Reloadorrestart("reload-or-restart"),
        Restart("restart"),
        Setproperty("set-property"),
        Show("show"),
        Start("start"),
        Status("status"),
        Stop("stop"),
        Thaw("thaw"),
        Tryreloadorrestart("try-reload-or-restart"),
        Tryrestart("try-restart"),
        Unmask("unmask");

        private final String value;

        SystemctlCommand(String value) {
            this.value = Objects.requireNonNull(value);
        }

        @EnumType.Converter
        public String getValue() {
            return this.value;
        }

        @Override
        public String toString() {
            return new StringJoiner(", ", "SystemctlCommand[", "]")
                .add("value='" + this.value + "'")
                .toString();
        }
    }
