# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from enum import Enum

__all__ = [
    'CommandLifecycle',
    'CurlCertType',
    'CurlDelegationLevel',
    'EtcdctlCommand',
    'HostnamectlCommand',
    'HostnamectlJsonMode',
    'SystemctlCommand',
    'TeeMode',
]


class CommandLifecycle(str, Enum):
    CREATE = "create"
    UPDATE = "update"
    DELETE = "delete"


class CurlCertType(str, Enum):
    PEM = "PEM"
    DER = "DER"
    ENG = "ENG"
    P12 = "P12"


class CurlDelegationLevel(str, Enum):
    NONE = "none"
    POLICY = "policy"
    ALWAYS = "always"


class EtcdctlCommand(str, Enum):
    MEMBER = "member"
    LIST = "list"
    VERSION = "version"


class HostnamectlCommand(str, Enum):
    STATUS = "status"
    """
    Show system hostname and related information. If no command is specified, this is the implied default.
    """
    HOSTNAME = "hostname"
    """
    If no argument is given, print the system hostname. If an optional argument NAME is provided then the command changes the system hostname to NAME.
    """
    ICON_NAME = "icon-name"
    """
    If no argument is given, print the icon name of the system. If an optional argument NAME is provided then the command changes the icon name to NAME.
    """
    CHASSIS = "chassis"
    """
    If no argument is given, print the chassis type. If an optional argument TYPE is provided then the command changes the chassis type to TYPE.
    """
    DEPLOYMENT = "deployment"
    """
    If no argument is given, print the deployment environment. If an optional argument ENVIRONMENT is provided then the command changes the deployment environment to ENVIRONMENT.
    """
    LOCATION = "location"
    """
    If no argument is given, print the location string for the system. If an optional argument LOCATION is provided then the command changes the location string for the system to LOCATION.
    """


class HostnamectlJsonMode(str, Enum):
    SHORT = "short"
    PRETTY = "pretty"
    OFF = "off"


class SystemctlCommand(str, Enum):
    BIND = "bind"
    CAT = "cat"
    CLEAN = "clean"
    DAEMON_RELOAD = "daemon-reload"
    DISABLE = "disable"
    ENABLE = "enable"
    FREEZE = "freeze"
    IS_ACTIVE = "is-active"
    IS_ENABLED = "is-enabled"
    IS_FAILED = "is-failed"
    ISOLATE = "isolate"
    KILL = "kill"
    LIST_AUTOMOUNTS = "list-automounts"
    LIST_DEPENDENCIES = "list-dependencies"
    LIST_PATHS = "list-paths"
    LIST_SOCKETS = "list-sockets"
    LIST_TIMERS = "list-timers"
    LIST_UNITS = "list-units"
    MASK = "mask"
    MOUNT_IMAGE = "mount-image"
    REENABLE = "reenable"
    RELOAD = "reload"
    RELOAD_OR_RESTART = "reload-or-restart"
    RESTART = "restart"
    SET_PROPERTY = "set-property"
    SHOW = "show"
    START = "start"
    STATUS = "status"
    STOP = "stop"
    THAW = "thaw"
    TRY_RELOAD_OR_RESTART = "try-reload-or-restart"
    TRY_RESTART = "try-restart"
    UNMASK = "unmask"


class TeeMode(str, Enum):
    WARN = "warn"
    WARN_NOPIPE = "warn-nopipe"
    EXIT = "exit"
    EXIT_NOPIPE = "exit-nopipe"
