// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.Commandx.Remote.Inputs
{

    /// <summary>
    /// Abstraction over the `rm` utility on a remote system.
    /// </summary>
    public sealed class RmOptsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Corresponds to the `--dir` option.
        /// </summary>
        [Input("dir")]
        public Input<bool>? Dir { get; set; }

        [Input("files", required: true)]
        private InputList<string>? _files;

        /// <summary>
        /// Corresponds to the [FILE] argument.
        /// </summary>
        public InputList<string> Files
        {
            get => _files ?? (_files = new InputList<string>());
            set => _files = value;
        }

        /// <summary>
        /// Corresponds to the `--force` option.
        /// </summary>
        [Input("force")]
        public Input<bool>? Force { get; set; }

        /// <summary>
        /// Whether rm should be run when the resource is created or deleted.
        /// </summary>
        [Input("onDelete")]
        public Input<bool>? OnDelete { get; set; }

        /// <summary>
        /// Corresponds to the `--recursive` option.
        /// </summary>
        [Input("recursive")]
        public Input<bool>? Recursive { get; set; }

        /// <summary>
        /// Corresponds to the `--verbose` option.
        /// </summary>
        [Input("verbose")]
        public Input<bool>? Verbose { get; set; }

        public RmOptsArgs()
        {
        }
        public static new RmOptsArgs Empty => new RmOptsArgs();
    }
}
