// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.Commandx.Remote.Inputs
{

    /// <summary>
    /// Abstraction over the `systemctl` utility on a remote system.
    /// </summary>
    public sealed class SystemctlOptsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Corresponds to the COMMAND argument.
        /// </summary>
        [Input("command", required: true)]
        public UnMango.Commandx.Remote.SystemctlCommand Command { get; set; }

        /// <summary>
        /// Corresponds to the `--now` option.
        /// </summary>
        [Input("now")]
        public Input<bool>? Now { get; set; }

        /// <summary>
        /// Corresponds to the [PATTERN] argument
        /// </summary>
        [Input("pattern")]
        public Input<string>? Pattern { get; set; }

        /// <summary>
        /// Corresponds to the [UNIT...] argument.
        /// </summary>
        [Input("unit", required: true)]
        public Input<string> Unit { get; set; } = null!;

        public SystemctlOptsArgs()
        {
        }
        public static new SystemctlOptsArgs Empty => new SystemctlOptsArgs();
    }
}
