// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.Commandx.Remote.Inputs
{

    /// <summary>
    /// Abstraction over the `rm` utility on a remote system.
    /// </summary>
    public sealed class TeeOptsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Append to the given FILEs, do not overwrite
        /// </summary>
        [Input("append")]
        public Input<bool>? Append { get; set; }

        [Input("files", required: true)]
        private InputList<string>? _files;

        /// <summary>
        /// Corresponds to the [FILE] argument.
        /// </summary>
        public InputList<string> Files
        {
            get => _files ?? (_files = new InputList<string>());
            set => _files = value;
        }

        /// <summary>
        /// Ignore interrupt signals.
        /// </summary>
        [Input("ignoreInterrupts")]
        public Input<bool>? IgnoreInterrupts { get; set; }

        /// <summary>
        /// Set behavior on write error.
        /// </summary>
        [Input("outputError")]
        public Input<UnMango.Commandx.Remote.TeeMode>? OutputError { get; set; }

        /// <summary>
        /// Operate in a more appropriate MODE with pipes.
        /// </summary>
        [Input("pipe")]
        public Input<bool>? Pipe { get; set; }

        /// <summary>
        /// Output version information and exit.
        /// </summary>
        [Input("version")]
        public Input<bool>? Version { get; set; }

        public TeeOptsArgs()
        {
        }
        public static new TeeOptsArgs Empty => new TeeOptsArgs();
    }
}
