// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.Commandx.Remote.Inputs
{

    /// <summary>
    /// Abstraction over the `wget` utility on a remote system.
    /// </summary>
    public sealed class WgetOptsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The  directory prefix is the directory where all other files and subdirectories will be saved to, i.e. the top of the retrieval tree.  The default is . (the current directory).
        /// </summary>
        [Input("directoryPrefix")]
        public Input<string>? DirectoryPrefix { get; set; }

        /// <summary>
        /// When in recursive mode, only HTTPS links are followed.
        /// </summary>
        [Input("httpsOnly")]
        public Input<bool>? HttpsOnly { get; set; }

        /// <summary>
        /// Turn off verbose without being completely quiet (use -q for that), which means that error messages and basic information still get printed.
        /// </summary>
        [Input("noVerbose")]
        public Input<bool>? NoVerbose { get; set; }

        /// <summary>
        /// The  documents  will  not  be  written  to the appropriate files, but all will be concatenated together and written to file.
        /// </summary>
        [Input("outputDocument")]
        public Input<string>? OutputDocument { get; set; }

        /// <summary>
        /// Turn off Wget's output.
        /// </summary>
        [Input("quiet")]
        public Input<bool>? Quiet { get; set; }

        /// <summary>
        /// Turn on time-stamping.
        /// </summary>
        [Input("timestamping")]
        public Input<bool>? Timestamping { get; set; }

        [Input("url", required: true)]
        private InputList<string>? _url;

        /// <summary>
        /// Corresponds to the [URL...] argument.
        /// </summary>
        public InputList<string> Url
        {
            get => _url ?? (_url = new InputList<string>());
            set => _url = value;
        }

        public WgetOptsArgs()
        {
        }
        public static new WgetOptsArgs Empty => new WgetOptsArgs();
    }
}
