// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.Commandx.Remote.Outputs
{

    /// <summary>
    /// Abstraction over the `mkdir` utility on a remote system.
    /// </summary>
    [OutputType]
    public sealed class MkdirOpts
    {
        /// <summary>
        /// The fully qualified path of the directory on the remote system.
        /// </summary>
        public readonly string Directory;
        /// <summary>
        /// Corresponds to the `--parents` option.
        /// </summary>
        public readonly bool? Parents;
        /// <summary>
        /// Remove the created directory when the `Mkdir` resource is deleted or updated.
        /// </summary>
        public readonly bool? RemoveOnDelete;

        [OutputConstructor]
        private MkdirOpts(
            string directory,

            bool? parents,

            bool? removeOnDelete)
        {
            Directory = directory;
            Parents = parents;
            RemoveOnDelete = removeOnDelete;
        }
    }
}
