// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.Commandx.Remote.Outputs
{

    /// <summary>
    /// Abstraction over the `wget` utility on a remote system.
    /// </summary>
    [OutputType]
    public sealed class WgetOpts
    {
        /// <summary>
        /// The  directory prefix is the directory where all other files and subdirectories will be saved to, i.e. the top of the retrieval tree.  The default is . (the current directory).
        /// </summary>
        public readonly string? DirectoryPrefix;
        /// <summary>
        /// When in recursive mode, only HTTPS links are followed.
        /// </summary>
        public readonly bool? HttpsOnly;
        /// <summary>
        /// Turn off verbose without being completely quiet (use -q for that), which means that error messages and basic information still get printed.
        /// </summary>
        public readonly bool? NoVerbose;
        /// <summary>
        /// The  documents  will  not  be  written  to the appropriate files, but all will be concatenated together and written to file.
        /// </summary>
        public readonly string? OutputDocument;
        /// <summary>
        /// Turn off Wget's output.
        /// </summary>
        public readonly bool? Quiet;
        /// <summary>
        /// Turn on time-stamping.
        /// </summary>
        public readonly bool? Timestamping;
        /// <summary>
        /// Corresponds to the [URL...] argument.
        /// </summary>
        public readonly ImmutableArray<string> Url;

        [OutputConstructor]
        private WgetOpts(
            string? directoryPrefix,

            bool? httpsOnly,

            bool? noVerbose,

            string? outputDocument,

            bool? quiet,

            bool? timestamping,

            ImmutableArray<string> url)
        {
            DirectoryPrefix = directoryPrefix;
            HttpsOnly = httpsOnly;
            NoVerbose = noVerbose;
            OutputDocument = outputDocument;
            Quiet = quiet;
            Timestamping = timestamping;
            Url = url;
        }
    }
}
